### PR TITLE
Don't error when parsing chiral SMILES

### PR DESCRIPTION
**Pull request by timholy**
There's a fair amount of work that would be needed to provide full support for chiral SMILES, but not throwing an error is at least a start.

See the spec: http://opensmiles.org/opensmiles.html#chirality

### CODE REVIEW

**Comment by caseykneale** [comment]
I did want to go the way of supporting full chirality - but chickened out to cut a quick release for a hobby project that failed to launch. I want to refactor some of the parsing here at some point, it's pretty squirrely... But - for now this is definitely a good idea.

**Comment by timholy** [comment]
Along these lines, how do you feel about minor cleanups of parsing? Want 'em?

**Comment by caseykneale** [comment]
If you are willing to clean up anything in here - fire away. I wrote the majority of this over the course of a weekend only focussing on small molecules - I've learned much better control structures, etc since then. Looking over some of this I'm shaking my head... I've had to dedicate time to some learning/brushing up on other areas lately.

Feel free to rip up, correct, improve, remove, anything you want so long as we can keep the same functionality or better. No consternation from me.

**Comment by caseykneale** [comment]
Also worth noting. Major changes have happened to LightGraphs since this was released... Might need to do some touchups there as well to get the full benefit of having SMILES(ish) -> Graph.

**Pull request merged**
